In [2]:
import torch

In [3]:
torch.__version__

'2.3.0+cu121'

In [4]:
scalar = torch.tensor(7)

In [5]:
print(scalar)

tensor(7)


In [8]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [23]:
vector.shape

torch.Size([2])

In [24]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [25]:
matrix.ndim

2

In [26]:
matrix.shape

torch.Size([2, 2])

In [27]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
tensor.shape

torch.Size([1, 3, 3])

In [29]:
tensor.ndim

3

In [30]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3400, 0.2136, 0.0789, 0.2460],
        [0.4287, 0.0401, 0.1275, 0.8285],
        [0.2636, 0.9930, 0.6945, 0.0062]])

In [31]:
random_tensor.ndim

2

In [32]:
random_tensor.shape

torch.Size([3, 4])

In [34]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [35]:
random_image_size_tensor.ndim

3

In [36]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
zeros.dtype

torch.float32

In [39]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
zero_to_ten_deprecated = torch.arange(0,10)
zero_to_ten_deprecated

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
torch.arange(start=0,end=100,step=10)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.zeros_like(input=zero_to_ten_deprecated)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_32_tensor.device

device(type='cpu')

In [47]:
tensor = torch.ones(size=(3,4))
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
tensor + 10

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [49]:
tensor * 20

tensor([[20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.]])

In [51]:
tensor / 100

tensor([[0.0100, 0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100, 0.0100]])

In [54]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [58]:
torch.arange(1, 100, 10)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
tensor * tensor * tensor

tensor([ 1,  8, 27])

In [64]:
torch.multiply(tensor , 10)

tensor([10, 20, 30])

In [66]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [67]:
tensor @ tensor

tensor(14)

In [68]:
1*1 + 2*2 + 3*3

14

In [69]:
tensor.multiply(tensor)

tensor([1, 4, 9])

In [91]:
tensor_a = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])


tensor_b = torch.tensor([[4, 2, 1],
                         [4, 2, 1],
                         [44, 3, 10]])


In [92]:
tensor_a * tensor_b

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [87]:
tensor_a.shape

torch.Size([2, 3])

In [88]:
tensor_b.shape

torch.Size([3, 3])

In [93]:
torch.matmul(tensor_a, tensor_b)

tensor([[144,  15,  33],
        [300,  36,  69]])

In [94]:
torch.manual_seed(42)

In [110]:
linear = torch.nn.Linear(in_features=3, out_features=3)

In [111]:
linear

Linear(in_features=3, out_features=3, bias=True)

In [112]:
linear.weight

Parameter containing:
tensor([[ 0.0900,  0.4665,  0.0631],
        [-0.1821,  0.1551, -0.1566],
        [ 0.2430,  0.5155,  0.3337]], requires_grad=True)

In [120]:
x = torch.tensor([[1,2,4], [1,5,4], [6,10,7]], dtype=torch.float32)

In [121]:
x

tensor([[ 1.,  2.,  4.],
        [ 1.,  5.,  4.],
        [ 6., 10.,  7.]])

In [122]:
linear(x)

tensor([[ 1.0230, -0.1648,  2.7122],
        [ 2.4224,  0.3006,  4.2586],
        [ 5.3941, -0.3039,  9.0521]], grad_fn=<AddmmBackward0>)

In [130]:
x = torch.arange(0, 100, 10, dtype = torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [131]:
x.min()

tensor(0.)

In [132]:
x.max()

tensor(90.)

In [133]:
x.mean()

tensor(45.)

In [134]:
torch.mean(x.type(torch.float16))

tensor(45., dtype=torch.float16)

In [135]:
x.argmax()

tensor(9)

In [136]:
tensor

tensor([1, 2, 3])

In [137]:
tensor.type(torch.float32)

tensor([1., 2., 3.])

In [138]:
import torch

In [139]:
x = torch.arange(1.0, 8.0)

In [140]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [142]:
tensor.type(torch.float32).mean()

tensor(2.)

In [143]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [144]:
x.mean()

tensor(4.)

In [147]:
x.reshape(1, 7)

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [148]:
z = x.view(1, 7)

In [149]:
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [150]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [151]:
z[: , 0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [152]:
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [155]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [156]:
x_squeeze = x_stacked.squeeze()
x_squeeze

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [157]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [158]:
x.shape

torch.Size([1, 3, 3])

In [159]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [160]:
x[0][0]

tensor([1, 2, 3])

In [161]:
x[0][0][0]

tensor(1)

In [162]:
import numpy as np
import torch

In [163]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

In [164]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [165]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [166]:
array = array.copy()
array

array([1., 2., 3., 4., 5., 6., 7.])

In [167]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [169]:
array = tensor.numpy()
array

array([1., 2., 3., 4., 5., 6., 7.])

In [170]:
torch.cuda.is_available()

False

In [171]:
torch.cuda.device_count()

0